imports:
    - php
build:
    environment:
        php:
            version: 5.6
tools:
    php_changetracking: true
    php_sim: true
    php_pdepend: true
    php_mess_detector: true
    php_hhvm: true
    php_analyzer: true
    php_cs_fixer: true
    sensiolabs_security_checker: true
    external_code_coverage: true