imports:
    - php

tools:
    #php_cpd: true
    php_sim: true
    php_pdepend: true
    php_mess_detector: true
    php_hhvm: true
    php_analyzer: true
    external_code_coverage:
            timeout: 600 # Timeout in seconds.
