imports:
    - php
build:
    environment:
        php:
            version: 7.3
    tests:
        override:
            - php-scrutinizer-run --enable-security-analysis
            -
               command: ./vendor/bin/phpunit --coverage-clover=coverage
               coverage:
                   file: coverage
                   format: php-clover
checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - 'test/*'
tools:
    php_changetracking: true
    php_sim: true
    php_pdepend: true
    php_mess_detector: true
    php_analyzer: true
    php_cs_fixer: true
    sensiolabs_security_checker: true