<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'General\Controller\IndexController' => __DIR__ . '/src/General/Controller/IndexController.php',
  'General\Controller\StyleController' => __DIR__ . '/src/General/Controller/StyleController.php',
  'General\Entity\CommunityType'       => __DIR__ . '/src/General/Entity/CommunityType.php',
  'General\Entity\ContentType'         => __DIR__ . '/src/General/Entity/ContentType.php',
  'General\Entity\Country'             => __DIR__ . '/src/General/Entity/Country.php',
  'General\Entity\EntityAbstract'      => __DIR__ . '/src/General/Entity/EntityAbstract.php',
  'General\Entity\EntityInterface'     => __DIR__ . '/src/General/Entity/EntityInterface.php',
  'General\Entity\Eu'                  => __DIR__ . '/src/General/Entity/Eu.php',
  'General\Entity\Gender'              => __DIR__ . '/src/General/Entity/Gender.php',
  'General\Entity\HydrateInterface'    => __DIR__ . '/src/General/Entity/HydrateInterface.php',
  'General\Entity\Title'               => __DIR__ . '/src/General/Entity/Title.php',
  'General\Entity\Vat'                 => __DIR__ . '/src/General/Entity/Vat.php',
  'General\Entity\VatType'             => __DIR__ . '/src/General/Entity/VatType.php',
  'General\Module'                     => __DIR__ . '/src/General/Module.php',
  'General\Options\ModuleOptions'      => __DIR__ . '/src/General/Options/ModuleOptions.php',
  'General\View\Helper\CountryMap'     => __DIR__ . '/src/General/View/Helper/CountryMap.php',
);
