<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'General\Controller\IndexController' => __DIR__ . '/src/General/Controller/IndexController.php',
    'General\Controller\StyleController' => __DIR__ . '/src/General/Controller/StyleController.php',
    'General\Entity\EntityAbstract'      => __DIR__ . '/src/General/Entity/EntityAbstract.php',
    'General\Entity\EntityInterface'     => __DIR__ . '/src/General/Entity/EntityInterface.php',
    'General\Entity\Gender'              => __DIR__ . '/src/General/Entity/Gender.php',
    'General\Entity\HydrateInterface'    => __DIR__ . '/src/General/Entity/HydrateInterface.php',
    'General\Entity\Title'               => __DIR__ . '/src/General/Entity/Title.php',
    'General\Module'                     => __DIR__ . '/src/General/Module.php',
    'General\Options\ModuleOptions'      => __DIR__ . '/src/General/Options/ModuleOptions.php',
);
